### ISSUE TITLE
Marine Plastic Layer Raw Data

### ISSUE THREAD

**Issue by jmhatch** [OHI-Science/ohiprep_v2020#1]
I'm trying to re-create the raster images of the marine plastic layers for each size class. It appears that OHI-Science has already rasterized the data provided by [Eriksen et al. 2014](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0111913). I'm just not sure where those data (GeoTiffs) are housed. From the code, they appear to be named `weight_density_size<#>_180_2.tif`. Could someone point me to their location? Also, to the location of the 1km grid they eventually get re-sampled to (`ocean.tif`)?

**Comment by jamiecmontgomery** [comment]
Hi @jmhatch 

You can download the `ocean.tif` raster by going here: https://mazu.nceas.ucsb.edu/data/, scroll to **Additional OHI Region data**  then click on "Download additional OHI region files" which will give you a zip file that includes that raster.

![image](https://user-images.githubusercontent.com/6842510/84697826-a965b880-af03-11ea-9bc2-18e14062e7c9.png)

The `weight_density_size` raster is held on our work servers so not accessible on GitHub. I can provide them to you via email? Do you want all four size classes?

**Comment by jmhatch** [comment]
Thanks @jamiecmontgomery! 

Email is fine -> joshua.hatch@noaa.gov. 

And yes, I'd like all four size classes if possible.
